version: "3.1"
services:

#  appdata:
#    build:
#      context: .
#      args:
#        - APP_ROOT
#    volumes:
#      - ./application/site:/var/www/site
#      - ./dynamic-data/site/.composer:/var/www/.composer
#      - ./source_code:/var/www/site


    mysql:
      image: mysql:5.7
      container_name: mysql
      working_dir: /application
      volumes:
        - ./application:/application
      env_file: .env
      networks:
        oro_net:
          ipv4_address: 10.5.0.10


    webserver:
      build: nginx
      container_name: webbserver
      working_dir: /application
      env_file: .env
      volumes:
        - ./application:/application
        - ./application/logs:/var/log/nginx
        - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
        - "443:443"
      networks:
        oro_net:
          ipv4_address: 10.5.0.15

    oro:
      build: oro
      container_name: oro
      working_dir: /application
      ports:
        - "8080:8080"
        - "9000:9000"
      env_file: .env
      depends_on:
        - webserver
        - mysql
      volumes:
        - ./application:/application
        - ./conf/parameters.yml:/application/parameters.yml
#        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      networks:
        oro_net:
          ipv4_address: 10.5.0.20

networks:
  docker-network:
    driver: bridge
  oro_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24
